### ISSUE TITLE
建議：修改部件

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [max32002/nanifont#1]
台標的是「囪」，港標的是「囱」。
你把部分字體的「囱」改一下，就是「窗」「聰」「總」「蔥」「傯」「璁」等部分。
還有，眾下邊的是三人，聚下方部分需要修改一下，比如「驟」「鄹」等部分。

**Comment by max32002** [comment]
ver 1.033 調整「囱」部件為台標的「囪」,更新清單：窗聰總蔥傯璁

**Comment by UltimateAmitieKaiNiC** [comment]
還有你的所有日系字體也要這樣呀！

**Comment by UltimateAmitieKaiNiC** [comment]
要求：眾潀聚驟鄹骤窻驄骢

**Comment by UltimateAmitieKaiNiC** [comment]
BUG：嘲的口字旁變成日了

**Comment by max32002** [comment]
> BUG：嘲的口字旁變成日了

ver 1.034 調整「嘲」字的部首為「口」，修正原作者的錯誤。

**Comment by UltimateAmitieKaiNiC** [comment]
建議調整【眾潀聚驟鄹骤窻驄骢】

**Comment by UltimateAmitieKaiNiC** [comment]
![image](https://user-images.githubusercontent.com/67255901/122659189-d2202e00-d1a7-11eb-8e39-270287113d67.png)

**Comment by UltimateAmitieKaiNiC** [comment]
看看這個，調整一些【眾潀聚驟鄹骤窻驄骢】

**Comment by max32002** [comment]
骤窻骢，按照google 的 CJK TC 裡的規則，似乎是應該套用日系寫法。
請重新下載 ver 1.036

**Comment by UltimateAmitieKaiNiC** [comment]
我明白了，修改的只是由正體中文為主。
